# Generated by Django 5.1.1 on 2024-10-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BinaryCityApp', '0006_alter_contact_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BinaryCityApp.client'),
        ),
    ]
